os: osx
osx_image: xcode10.2
language: node_js
node_js: "10.16.3"

env:
  global:
    - JOBS=4
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

script:
  - npm run electron:build -- -ml --ia32 --x64

addons:
  homebrew:
    packages:
    - rpm